/*
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */


/*
 * A simple in-memory key-value store for base64 image data.
 *
 * This object acts as a cache to hold the input (from webcam) and output (from AI) images.
 * Storing large base64 strings outside of the main Zustand state helps prevent
 * performance issues and keeps the state object lightweight and serializable.
 * The keys for both `inputs` and `outputs` are the unique photo IDs generated on creation.
 */
export default {
  /*
   * Stores the base64 data of the original photos taken by the user.
   * @type {Object.<string, string>}
   */
  inputs: {},

  /*
   * Stores the base64 data of the final images generated by the AI.
   * @type {Object.<string, string>}
   */
  outputs: {}
}
